coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  comment:
    layout: "reach, diff, files"  # Remove items here to change the format